### 주문 생성
POST localhost:19091/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoiY3VzdG9tZXJJZCIsInJvbGUiOiJDVVNUT01FUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczMzE5NDk2MSwiZXhwIjoxNzMzMTk4NTYxfQ.ZcIyrutVvPM8N01RIx4hCsMH6DxJi46zAfu-ypVzUlOCRA3PL8rwWc0ukfjRAP3tYLzYZk4sDF9wodVRM0DgSw

{
  "productIds": [
    1,
    2
  ]
}

### 주문 실패
POST localhost:19091/orders?fail=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoiY3VzdG9tZXJJZCIsInJvbGUiOiJDVVNUT01FUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczMzE5NDk2MSwiZXhwIjoxNzMzMTk4NTYxfQ.ZcIyrutVvPM8N01RIx4hCsMH6DxJi46zAfu-ypVzUlOCRA3PL8rwWc0ukfjRAP3tYLzYZk4sDF9wodVRM0DgSw

{
  "productIds": [
    1,
    2
  ]
}

### 주문 업데이트
PUT localhost:19091/orders/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoiY3VzdG9tZXJJZCIsInJvbGUiOiJDVVNUT01FUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczMzIwMjQ3MSwiZXhwIjoxNzMzMjA2MDcxfQ.1hFtNs2dSTUeBQ1vmQMOB7Yk5KQavK-S1tzzbx8RESv2RMKsDXQHIYfpQIHVhhvOlbjwrOxRz58uzdUYGgyj_Q

{
  "productIds": [
    3,
    4
  ]
}