server:
  port: ${SERVER_PORT:19093}

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST}:3306/msadb
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}
