### 상품 등록
POST localhost:19091/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoicGF0dElkIiwicm9sZSI6Ik1BTkFHRVIiLCJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3MzMxMTY1MDYsImV4cCI6MTczMzEyMDEwNn0.IJZEgL1KD5sFFJxprW5fz4u5T3d2T72H8I5unoaXbMEKlkz7-0EZHMCWZw3zJmT0FXBfFJGY-KktCWCNRP_hFQ

{
  "name": "Pencil",
  "supplyPrice": "15000"
}