### 상품 등록
POST localhost:19091/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjoic2lsbHlJZCIsInJvbGUiOiJDVVNUT01FUiIsImlzcyI6ImF1dGgtc2VydmljZSIsImlhdCI6MTczMzExNzE3OSwiZXhwIjoxNzMzMTIwNzc5fQ.5wI7ipjNIWLWhuPqMQcO6U5DSpE23ugkosqt1pqXl7E8PUQ2RCZZQZMmLs42hEQy7AacyVGi5ybCl9QVlgvT8A

{
  "name": "phone",
  "supplyPrice": "16000"
}