spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST}:3306/msadb
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

server:
  port: ${SERVER_PORT}