server:
  port: ${GATEWAY_PORT:19091}

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: WeightedLoadBalancerFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:19090}/eureka/