### 회원가입
POST localhost:19091/auth/sign-up
Content-Type: application/json

{
  "userId": "pitId",
  "username": "pit",
  "password": "1234",
  "role": "manager"
}

### 로그인
POST localhost:19091/auth/sign-in
Content-Type: application/json

{
  "userId": "daveId",
  "password": "1234"
}